### PR TITLE
Add prefix to annotation

### PR DESCRIPTION
**Pull request by heroic**
Add a default prefix

### CODE REVIEW

**Comment by jstrachan** [comment]
@heroic looks like this PR needs rebasing

**Comment by ccojocar** [comment]
@heroic Please could you rebase this PR? thanks

**Comment by heroic** [comment]
@ccojocar done!

**Comment by ccojocar** [comment]
@heroic This seems to have a compilation error:
```
CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags " -X github.com/jenkins-x/exposecontroller/version.Version='0.0.0-SNAPSHOT-PR-173-1' -X github.com/jenkins-x/exposecontroller/version.Revision='5162269' -X github.com/jenkins-x/exposecontroller/version.Branch='master' -X github.com/jenkins-x/exposecontroller/version.BuildUser='@jenkins-x-exposecontroller-pr-1-1-ci-kpkft-pod-b359d2' -X github.com/jenkins-x/exposecontroller/version.BuildDate='20190508-06:51:00' -X github.com/jenkins-x/exposecontroller/version.GoVersion='1.11.5' -s -w -extldflags '-static'" -o ./out/exposecontroller-linux-amd64 github.com/jenkins-x/exposecontroller
# github.com/jenkins-x/exposecontroller/exposestrategy
_gopath/src/github.com/jenkins-x/exposecontroller/exposestrategy/ambassador.go:135:10: invalid operation: path != nil (mismatched types string and nil)
```

**Comment by ccojocar** [comment]
This seems to be quite old. I am closing it for now. Please feel free to open a new pull request. Thanks!

**Pull request closed without merging**
