### PR TITLE
[WIP] Move to go modules

### PR DESCRIPTION
**Pull request by carlossg**
Keep some vendored modules because they can't be found
Or because Sirupsen/logrus needs to be renamed to sirupsen/logrus

### CODE REVIEW

**Comment by carlossg** [comment]
@ccojocar @pmuir I reached a point where I'm stuck trying to get this working 

I had to keep some vendored dirs to rename Sirupsen but now those don't build

```
vendor/github.com/docker/docker/pkg/archive/archive_unix.go:84:5: undefined: "github.com/opencontainers/runc/libcontainer/system".RunningInUserNS
```

If I have to add all the dependencies of `docker/docker` to `vendor/github.com/docker/docker/go.mod` it's a big pita, because those in turn need the `Sirupsen` rename.

**Comment by carlossg** [comment]
@ccojocar it doesn't work, see my comment above

**Comment by ccojocar** [comment]
Hmmm, how did you crate the go modules file? Did you run the `go mod init` command? I think some dependencies needs an update.

**Comment by ccojocar** [comment]
@carlossg Can I close this? Maybe we should start another PR to switch to go modules.

**Pull request closed without merging**
